[project]
name = "DART"
version = "6.14.0"
description = "Dynamic Animation and Robotics Toolkit"
authors = ["Jeongseok Lee <jslee02@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
configure = "cmake -G Ninja -S . -B build"
build = { cmd = "cmake --build build --parallel", depends_on = ["configure"] }

[dependencies]
assimp = ">=5.3.1,<5.4"
eigen = ">=3.4.0,<3.5"
bullet-cpp = ">=3.25,<4"
fcl = ">=0.7.0,<0.8"
libccd-double = ">=2.1,<3"
libode = ">=0.16.2,<0.17"
octomap = ">=1.9.8,<1.10"
tinyxml2 = ">=10.0.0,<10.1"
urdfdom = ">=4.0.0,<4.1"
fmt = ">=10.2.1,<10.3"
spdlog = ">=1.12.0,<1.13"
freeglut = ">=3.2.2,<3.3"

[build-dependencies]
cmake = "3.22.*"
ninja = ">=1.11.1,<1.12"
pkg-config = ">=0.29.2,<0.30"
